In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('bank.csv')
dataset

age          job  marital  education default  balance housing loan  \
0       59       admin.  married  secondary      no     2343     yes   no   
1       56       admin.  married  secondary      no       45      no   no   
2       41   technician  married  secondary      no     1270     yes   no   
3       55     services  married  secondary      no     2476     yes   no   
4       54       admin.  married   tertiary      no      184      no   no   
...    ...          ...      ...        ...     ...      ...     ...  ...   
11157   33  blue-collar   single    primary      no        1     yes   no   
11158   39     services  married  secondary      no      733      no   no   
11159   32   technician   single  secondary      no       29      no   no   
11160   43   technician  married  secondary      no        0      no  yes   
11161   34   technician  married  secondary      no        0      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome  \
0       unknown    5   may      1042         1     -1         0  unknown   
1       unknown    5   may      1467         1     -1         0  unknown   
2       unknown    5   may      1389         1     -1         0  unknown   
3       unknown    5   may       579         1     -1         0  unknown   
4       unknown    5   may       673         2     -1         0  unknown   
...         ...  ...   ...       ...       ...    ...       ...      ...   
11157  cellular   20   apr       257         1     -1         0  unknown   
11158   unknown   16   jun        83         4     -1         0  unknown   
11159  cellular   19   aug       156         2     -1         0  unknown   
11160  cellular    8   may         9         2    172         5  failure   
11161  cellular    9   jul       628         1     -1         0  unknown   

      deposit  
0         yes  
1         yes  
2         yes  
3         yes  
4         yes  
...       ...  
11157      no  
11158      no  
11159      no  
11160      no  
11161      no  

[11162 rows x 17 columns]

In [3]:
dataset['education'].value_counts()

secondary    5476
tertiary     3689
primary      1500
unknown       497
Name: education, dtype: int64

In [4]:
dataset['marital'].value_counts()

married     6351
single      3518
divorced    1293
Name: marital, dtype: int64

In [5]:
x=dataset.iloc[:,:16].values
x

array([[59, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [56, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [41, 'technician', 'married', ..., -1, 0, 'unknown'],
       ...,
       [32, 'technician', 'single', ..., -1, 0, 'unknown'],
       [43, 'technician', 'married', ..., 172, 5, 'failure'],
       [34, 'technician', 'married', ..., -1, 0, 'unknown']], dtype=object)

In [6]:
y=dataset.iloc[:,16:17].values
y

array([['yes'],
       ['yes'],
       ['yes'],
       ...,
       ['no'],
       ['no'],
       ['no']], dtype=object)

In [7]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [8]:
y=lb.fit_transform(y)
y

C:\Users\Aditya\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 1, 1, ..., 0, 0, 0])

In [9]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [10]:
dataset['deposit']=lb.fit_transform(dataset['deposit'])

In [11]:
dataset['housing']=lb.fit_transform(dataset['housing'])
dataset['loan']=lb.fit_transform(dataset['loan'])

In [12]:
a=dataset.drop(['contact','day','month','duration','campaign','pdays','previous','poutcome','default'],axis=1)

In [13]:
a

age          job  marital  education  balance  housing  loan  deposit
0       59       admin.  married  secondary     2343        1     0        1
1       56       admin.  married  secondary       45        0     0        1
2       41   technician  married  secondary     1270        1     0        1
3       55     services  married  secondary     2476        1     0        1
4       54       admin.  married   tertiary      184        0     0        1
...    ...          ...      ...        ...      ...      ...   ...      ...
11157   33  blue-collar   single    primary        1        1     0        0
11158   39     services  married  secondary      733        0     0        0
11159   32   technician   single  secondary       29        0     0        0
11160   43   technician  married  secondary        0        0     1        0
11161   34   technician  married  secondary        0        0     0        0

[11162 rows x 8 columns]

In [14]:
dataset['job'].value_counts()

management       2566
blue-collar      1944
technician       1823
admin.           1334
services          923
retired           778
self-employed     405
student           360
unemployed        357
entrepreneur      328
housemaid         274
unknown            70
Name: job, dtype: int64

In [15]:
b=a[["marital","job","education","age","balance","housing","loan","deposit"]]
b

marital          job  education  age  balance  housing  loan  deposit
0      married       admin.  secondary   59     2343        1     0        1
1      married       admin.  secondary   56       45        0     0        1
2      married   technician  secondary   41     1270        1     0        1
3      married     services  secondary   55     2476        1     0        1
4      married       admin.   tertiary   54      184        0     0        1
...        ...          ...        ...  ...      ...      ...   ...      ...
11157   single  blue-collar    primary   33        1        1     0        0
11158  married     services  secondary   39      733        0     0        0
11159   single   technician  secondary   32       29        0     0        0
11160  married   technician  secondary   43        0        0     1        0
11161  married   technician  secondary   34        0        0     0        0

[11162 rows x 8 columns]

In [16]:
b['marital']=lb.fit_transform(b['marital'])
b['job']=lb.fit_transform(b['job'])
b['education']=lb.fit_transform(b['education'])

b

marital  job  education  age  balance  housing  loan  deposit
0            1    0          1   59     2343        1     0        1
1            1    0          1   56       45        0     0        1
2            1    9          1   41     1270        1     0        1
3            1    7          1   55     2476        1     0        1
4            1    0          2   54      184        0     0        1
...        ...  ...        ...  ...      ...      ...   ...      ...
11157        2    1          0   33        1        1     0        0
11158        1    7          1   39      733        0     0        0
11159        2    9          1   32       29        0     0        0
11160        1    9          1   43        0        0     1        0
11161        1    9          1   34        0        0     0        0

[11162 rows x 8 columns]

In [17]:
b

marital  job  education  age  balance  housing  loan  deposit
0            1    0          1   59     2343        1     0        1
1            1    0          1   56       45        0     0        1
2            1    9          1   41     1270        1     0        1
3            1    7          1   55     2476        1     0        1
4            1    0          2   54      184        0     0        1
...        ...  ...        ...  ...      ...      ...   ...      ...
11157        2    1          0   33        1        1     0        0
11158        1    7          1   39      733        0     0        0
11159        2    9          1   32       29        0     0        0
11160        1    9          1   43        0        0     1        0
11161        1    9          1   34        0        0     0        0

[11162 rows x 8 columns]

In [18]:
b.shape

(11162, 8)

In [19]:
from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import ColumnTransformer 

In [20]:
ct=ColumnTransformer([("on",OneHotEncoder(),[0])],remainder='passthrough')
b=ct.fit_transform(b)
b

array([[0., 1., 0., ..., 1., 0., 1.],
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 1., 0., 1.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [21]:
b.shape

(11162, 10)

In [22]:
b=b[:,1:]
b

array([[1., 0., 0., ..., 1., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 9., ..., 1., 0., 1.],
       ...,
       [0., 1., 9., ..., 0., 0., 0.],
       [1., 0., 9., ..., 0., 1., 0.],
       [1., 0., 9., ..., 0., 0., 0.]])

In [23]:
b.shape


(11162, 9)

In [24]:
c=b
c

array([[1., 0., 0., ..., 1., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 9., ..., 1., 0., 1.],
       ...,
       [0., 1., 9., ..., 0., 0., 0.],
       [1., 0., 9., ..., 0., 1., 0.],
       [1., 0., 9., ..., 0., 0., 0.]])

In [25]:
ct=ColumnTransformer([("on",OneHotEncoder(),[2])],remainder='passthrough')
c=ct.fit_transform(c)
c

array([[1., 0., 0., ..., 1., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [26]:
c=c[:,1:]
c

array([[0., 0., 0., ..., 1., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [27]:
c.shape

(11162, 19)

In [28]:
d=c
d

array([[0., 0., 0., ..., 1., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [29]:
ct=ColumnTransformer([("on",OneHotEncoder(),[-6])],remainder='passthrough')
d=ct.fit_transform(d)
d

array([[0., 1., 0., ..., 1., 0., 1.],
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 1., 0., 1.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [30]:
d.shape

(11162, 22)

In [31]:
d=d[:,1:]
d

array([[1., 0., 0., ..., 1., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 1.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [32]:
d.shape

(11162, 21)

In [33]:
from sklearn.model_selection import train_test_split
d_train,d_test,y_train,y_test=train_test_split(d,y,test_size=0.2,random_state=0)

In [34]:
from sklearn.linear_model import LinearRegression
mr=LinearRegression()

In [35]:
import sys
np.set_printoptions(threshold=sys.maxsize)
print(d)

[[ 1.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00
   0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00
   0.0000e+00  0.0000e+00  1.0000e+00  0.0000e+00  5.9000e+01  2.3430e+03
   1.0000e+00  0.0000e+00  1.0000e+00]
 [ 1.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00
   0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00
   0.0000e+00  0.0000e+00  1.0000e+00  0.0000e+00  5.6000e+01  4.5000e+01
   0.0000e+00  0.0000e+00  1.0000e+00]
 [ 1.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00
   0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  1.0000e+00
   0.0000e+00  0.0000e+00  1.0000e+00  0.0000e+00  4.1000e+01  1.2700e+03
   1.0000e+00  0.0000e+00  1.0000e+00]
 [ 1.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00
   0.0000e+00  0.0000e+00  0.0000e+00  1.0000e+00  0.0000e+00  0.0000e+00
   0.0000e+00  0.0000e+00  1.0000e+00  0.0000e+00  5.5000e+01  2.4760

In [36]:
mr.fit(d_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [37]:
from sklearn.metrics import r2_score
r2_score(y_test,mr.predict(d_test))

1.0

In [38]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor(n_estimators=10,random_state=0,n_jobs=-1)
rf.fit(d_train,y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=10, n_jobs=-1, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [39]:
y_pred=rf.predict(d_test)
y_pred

array([0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1.,
       0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1.,
       0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0.,
       1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1.,
       0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1.,
       0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1.,
       1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
       0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1.,
       0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0.,
       1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 1.

In [40]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

1.0

In [41]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
pipe=Pipeline([('rescale',StandardScaler()),('classifier', SVC(kernel='rbf'))
])

In [42]:
pipe.fit(d_train,y_train)

Pipeline(memory=None,
         steps=[('rescale',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('classifier',
                 SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None,
                     coef0=0.0, decision_function_shape='ovr', degree=3,
                     gamma='scale', kernel='rbf', max_iter=-1,
                     probability=False, random_state=None, shrinking=True,
                     tol=0.001, verbose=False))],
         verbose=False)

In [43]:
y_pred=pipe.predict(d_test)

In [44]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

1.0